'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/lib/auth/hooks'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { ArrowLeft, Save, FileText, Printer } from 'lucide-react'

export default function ActionPlanPage() {
  const { user, loading } = useAuth()
  const router = useRouter()
  
  // Action plan state
  const [title, setTitle] = useState('My Asthma Action Plan')
  const [greenZone, setGreenZone] = useState(`**GREEN ZONE - Good Control (80-100% of best peak flow)**

Symptoms:
• No coughing, wheezing, chest tightness, or shortness of breath
• Can sleep through the night
• Can do usual activities

Peak Flow: 400-500 L/min (80-100% of personal best)

**Daily Treatment:**
• Take controller medication as prescribed
• Continue normal activities
• Monitor for changes`)

  const [yellowZone, setYellowZone] = useState(`**YELLOW ZONE - Caution (50-79% of best peak flow)**

Symptoms:
• Mild coughing, wheezing, chest tightness, or shortness of breath
• Symptoms interfere with daily activities
• Wake up at night due to symptoms

Peak Flow: 250-399 L/min (50-79% of personal best)

**Treatment:**
• Continue controller medication
• Take rescue inhaler: 2-4 puffs every 20 minutes for up to 1 hour
• Rest and avoid triggers
• If no improvement in 1 hour, move to Red Zone treatment`)

  const [redZone, setRedZone] = useState(`**RED ZONE - Medical Alert (Below 50% of best peak flow)**

Symptoms:
• Severe breathing difficulty
• Cannot walk or talk normally
• Lips or fingernails are blue or gray
• Rescue medications not helping

Peak Flow: Below 250 L/min (Below 50% of personal best)

**Emergency Treatment:**
• Take rescue inhaler: 4-8 puffs immediately
• Call 911 or go to emergency room NOW
• Continue rescue medication every 20 minutes until help arrives
• Try to stay calm and sit upright

**Important:** This is a medical emergency!`)

  const [isSaving, setIsSaving] = useState(false)

  const handleSave = async () => {
    setIsSaving(true)
    try {
      // Simulate API call to save action plan
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      // In real app, would save to database
      console.log('Action plan saved:', {
        title,
        greenZone,
        yellowZone,
        redZone
      })
      
      // Show success and redirect
      router.push('/dashboard')
    } catch (error) {
      console.error('Error saving action plan:', error)
    } finally {
      setIsSaving(false)
    }
  }

  const handlePrint = () => {
    const printContent = `
      <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
            h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
            .zone { margin: 20px 0; padding: 15px; border-radius: 8px; }
            .green { background: #f0fdf4; border-left: 4px solid #22c55e; }
            .yellow { background: #fefce8; border-left: 4px solid #eab308; }
            .red { background: #fef2f2; border-left: 4px solid #ef4444; }
            pre { white-space: pre-wrap; font-family: inherit; }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <div class="zone green">
            <pre>${greenZone}</pre>
          </div>
          <div class="zone yellow">
            <pre>${yellowZone}</pre>
          </div>
          <div class="zone red">
            <pre>${redZone}</pre>
          </div>
          <p style="margin-top: 40px; text-align: center; color: #666; border-top: 1px solid #ddd; padding-top: 20px;">
            Generated by Asthma Buddy • ${new Date().toLocaleDateString()}
          </p>
        </body>
      </html>
    `
    
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(printContent)
      printWindow.document.close()
      printWindow.print()
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-2 text-sm text-gray-600">Loading...</p>
        </div>
      </div>
    )
  }

  if (!user) {
    router.push('/auth/login')
    return null
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-4">
            <Button
              variant="outline"
              size="sm"
              onClick={() => router.back()}
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Asthma Action Plan</h1>
              <p className="text-sm text-gray-600">
                Create and customize your personal asthma management plan
              </p>
            </div>
          </div>
          
          <div className="flex space-x-2">
            <Button variant="outline" onClick={handlePrint}>
              <Printer className="w-4 h-4 mr-2" />
              Print
            </Button>
            <Button onClick={handleSave} disabled={isSaving}>
              {isSaving ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                  Saving...
                </>
              ) : (
                <>
                  <Save className="w-4 h-4 mr-2" />
                  Save Plan
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Plan Title */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Plan Title</CardTitle>
          </CardHeader>
          <CardContent>
            <Input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="text-lg font-semibold"
              placeholder="My Asthma Action Plan"
            />
          </CardContent>
        </Card>

        {/* Action Plan Zones */}
        <Tabs defaultValue="green" className="space-y-6">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="green" className="text-green-700">
              🟢 Green Zone
            </TabsTrigger>
            <TabsTrigger value="yellow" className="text-yellow-700">
              🟡 Yellow Zone
            </TabsTrigger>
            <TabsTrigger value="red" className="text-red-700">
              🔴 Red Zone
            </TabsTrigger>
          </TabsList>

          <TabsContent value="green">
            <Card className="border-green-200">
              <CardHeader className="bg-green-50">
                <CardTitle className="text-green-800">Green Zone - Good Control</CardTitle>
                <CardDescription>
                  When you feel good and have no symptoms (80-100% of best peak flow)
                </CardDescription>
              </CardHeader>
              <CardContent className="pt-6">
                <div className="space-y-2">
                  <Label htmlFor="green-zone">Instructions</Label>
                  <Textarea
                    id="green-zone"
                    value={greenZone}
                    onChange={(e) => setGreenZone(e.target.value)}
                    className="min-h-[300px] font-mono text-sm"
                    placeholder="Enter your green zone instructions..."
                  />
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="yellow">
            <Card className="border-yellow-200">
              <CardHeader className="bg-yellow-50">
                <CardTitle className="text-yellow-800">Yellow Zone - Caution</CardTitle>
                <CardDescription>
                  When you have some symptoms (50-79% of best peak flow)
                </CardDescription>
              </CardHeader>
              <CardContent className="pt-6">
                <div className="space-y-2">
                  <Label htmlFor="yellow-zone">Instructions</Label>
                  <Textarea
                    id="yellow-zone"
                    value={yellowZone}
                    onChange={(e) => setYellowZone(e.target.value)}
                    className="min-h-[300px] font-mono text-sm"
                    placeholder="Enter your yellow zone instructions..."
                  />
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="red">
            <Card className="border-red-200">
              <CardHeader className="bg-red-50">
                <CardTitle className="text-red-800">Red Zone - Medical Alert</CardTitle>
                <CardDescription>
                  When you have severe symptoms (below 50% of best peak flow)
                </CardDescription>
              </CardHeader>
              <CardContent className="pt-6">
                <div className="space-y-2">
                  <Label htmlFor="red-zone">Instructions</Label>
                  <Textarea
                    id="red-zone"
                    value={redZone}
                    onChange={(e) => setRedZone(e.target.value)}
                    className="min-h-[300px] font-mono text-sm"
                    placeholder="Enter your red zone instructions..."
                  />
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Footer */}
        <div className="mt-8 p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <div className="flex items-start space-x-3">
            <FileText className="w-5 h-5 text-blue-600 mt-0.5" />
            <div className="text-sm text-blue-800">
              <p className="font-medium mb-1">Important Notes:</p>
              <ul className="list-disc list-inside space-y-1 text-blue-700">
                <li>This action plan should be developed with your healthcare provider</li>
                <li>Review and update your plan regularly with your doctor</li>
                <li>Keep a copy with you at all times</li>
                <li>Share copies with family, school, and workplace</li>
                <li>In case of emergency, call 911 immediately</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}